version: "3.7"

services:
  web:
    image: webdevops/php-apache:alpine-php7
    ports:
      - "4500:80"
    volumes:
      - /opt/docker_share/php/:/app

    networks:
      - minha-rede

  db:
    image: toshiro-shibakita-mysql
    environment:
      MYSQL_ROOT_PASSWORD: "QRBBpGvf58b5Hz"
      MYSQL_DATABASE: "meudb"
    ports:
      - "3306:3306"
    volumes:
      - /opt/docker_share/mysql:/var/lib/mysql

    networks:
      - minha-rede

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - /opt/docker_share/nginx/nginx.conf:/etc/nginx/nginx.conf

    networks:
      - minha-rede

networks:
   minha-rede:
     driver: overlay